# Generated by Django 4.2.7 on 2023-11-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=100, verbose_name='Origen')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('fechasalida', models.DateTimeField(verbose_name='Salida')),
                ('Escalado', models.BooleanField(verbose_name='Escalas')),
            ],
        ),
    ]
