# Generated by Django 4.2.7 on 2023-12-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='user email')),
                ('FullName', models.CharField(max_length=100, verbose_name='full name')),
            ],
        ),
        migrations.AddField(
            model_name='vuelo',
            name='Ida_vuelta',
            field=models.BooleanField(default=False, verbose_name='ida_vuelta'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='fechavuelta',
            field=models.DateTimeField(default='2023-12-01 00:00:00', verbose_name='vuelta_d'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fechasalida',
            field=models.DateTimeField(default='2023-12-01 00:00:00', verbose_name='Salida_d'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='puestos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(verbose_name='puesto')),
                ('Ejecutivo_bool', models.BooleanField(verbose_name='Ejecutivo o comercial')),
                ('Ventana_bool', models.BooleanField(verbose_name='Ventana o pasillo')),
                ('Vuelo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.vuelo')),
            ],
        ),
    ]
