# Generated by Django 4.2.7 on 2023-12-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_usuarios_vuelo_ida_vuelta_vuelo_fechavuelta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='fechasalida',
            field=models.DateTimeField(blank=True, default='2023-12-01 00:00:00', verbose_name='Salida_d'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fechavuelta',
            field=models.DateTimeField(blank=True, default='2023-12-01 00:00:00', verbose_name='vuelta_d'),
        ),
    ]
