# Generated by Django 4.2.7 on 2023-12-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_alter_vuelo_fechasalida_alter_vuelo_fechavuelta'),
    ]

    operations = [
        migrations.CreateModel(
            name='aerolinea',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_aerolinea', models.CharField(max_length=100, verbose_name='nombre')),
                ('logo_aerolinea', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='vuelo',
            name='escalas',
            field=models.IntegerField(blank=True, default=0, verbose_name='# escalas'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='precio',
            field=models.CharField(default='ND', max_length=100, verbose_name='Precio'),
        ),
        
    ]
