# Generated by Django 4.2.7 on 2023-12-15 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_aerolinea_vuelo_escalas_vuelo_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='id_aerolinea',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lib.aerolinea'),
        ),
    ]
