# Generated by Django 4.2.7 on 2023-12-15 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_vuelo_id_aerolinea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='id_aerolinea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.aerolinea'),
        ),
    ]
