# Generated by Django 4.2.7 on 2023-12-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_alter_vuelo_id_alter_vuelo_id_aerolinea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='fechasalida',
            field=models.DateTimeField(blank=True, verbose_name='Salida_d'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fechavuelta',
            field=models.DateTimeField(blank=True, verbose_name='vuelta_d'),
        ),
    ]
