# Generated by Django 4.2.7 on 2023-12-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_alter_vuelo_fechasalida_alter_vuelo_fechavuelta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerolinea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
