# Generated by Django 4.2.7 on 2023-12-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0008_alter_aerolinea_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
