# Generated by Django 4.2.7 on 2023-12-16 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_alter_puestos_id_alter_vuelo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatherclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sonclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('Father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.fatherclass')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
