# Generated by Django 4.2.7 on 2023-12-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0010_fatherclass_sonclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonclass',
            name='Father',
        ),
        migrations.DeleteModel(
            name='Fatherclass',
        ),
        migrations.DeleteModel(
            name='Sonclass',
        ),
    ]
