# Generated by Django 4.2.7 on 2023-12-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0011_remove_sonclass_father_delete_fatherclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerolinea',
            name='logo_aerolinea',
            field=models.ImageField(upload_to='logos_aerolineas'),
        ),
    ]
