# Generated by Django 4.2.7 on 2023-12-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0012_alter_aerolinea_logo_aerolinea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
