# Generated by Django 4.2.7 on 2023-12-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0013_delete_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='horasalida1',
            field=models.TimeField(blank=True, default="12:30:00", verbose_name='hora salida'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='horasalida2',
            field=models.TimeField(blank=True, default="12:30:00", verbose_name='hora llegada'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='horavuelta1',
            field=models.TimeField(blank=True, default="12:30:00", verbose_name='hora salida'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='horavuelta2',
            field=models.TimeField(blank=True, default="12:30:00", verbose_name='hora llegada'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fechasalida',
            field=models.DateField(blank=True, verbose_name='fecha salida'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fechavuelta',
            field=models.DateField(blank=True, verbose_name='fecha regreso'),
        ),
    ]
