# Generated by Django 4.2.7 on 2023-12-30 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib', '0014_vuelo_horasalida1_vuelo_horasalida2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='horasalida1',
            field=models.TimeField(blank=True, default=None, verbose_name='hora salida'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='horasalida2',
            field=models.TimeField(blank=True, default=None, verbose_name='hora llegada'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='horavuelta1',
            field=models.TimeField(blank=True, default=None, verbose_name='hora salida'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='horavuelta2',
            field=models.TimeField(blank=True, default=None, verbose_name='hora llegada'),
        ),
        migrations.CreateModel(
            name='userVueloYa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='default.jpg', upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
