# Generated by Django 4.2.7 on 2024-01-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0015_alter_vuelo_horasalida1_alter_vuelo_horasalida2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservueloya',
            name='fechaNacimiento',
            field=models.DateField(blank=True, default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='uservueloya',
            name='genero',
            field=models.CharField(default='No especificado', max_length=15),
        ),
        migrations.AddField(
            model_name='uservueloya',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='uservueloya',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='profile_pictures'),
        ),
    ]
