# Generated by Django 4.2.7 on 2024-01-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0017_alter_uservueloya_picture_userfacturacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userFacturacion',
        ),
    ]
