# Generated by Django 4.2.7 on 2024-01-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0019_historicoreserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoreserva',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
