# Generated by Django 4.2.7 on 2024-01-20 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0020_alter_historicoreserva_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='defaultbg.png', upload_to='imagen_ofertas')),
                ('descripcion', models.TextField()),
                ('vuelo', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='lib.vuelo')),
            ],
        ),
    ]
