# Generated by Django 4.2.7 on 2024-02-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0023_alter_uservueloya_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
    ]
