# Generated by Django 4.2.7 on 2024-02-15 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0024_alter_vuelo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='duracion1',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=1, seconds=19800), verbose_name='duracion'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='duracion2',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=1, seconds=19800), verbose_name='duracion'),
        ),
    ]
