# Generated by Django 4.2.7 on 2024-02-19 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0026_remove_vuelo_duracion1_remove_vuelo_duracion2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoreserva',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(days=1), verbose_name='total'),
        ),
    ]
