# Generated by Django 4.2.7 on 2024-09-07 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0027_historicoreserva_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='lugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=100, verbose_name='nombre')),
                ('image', models.ImageField(default='defaultbg.jpg', upload_to='imagen_ofertas')),
                ('descripcion', models.TextField()),
                ('vuelo', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='lib.vuelo')),
            ],
        ),
    ]
