# Generated by Django 4.2.7 on 2024-09-08 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0028_alter_puestos_id_lugarturistico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarturistico',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lib.vuelo'),
        ),
    ]
