# Generated by Django 4.2.7 on 2024-01-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userfacturacion_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfacturacion',
            name='situacionFiscal',
            field=models.CharField(max_length=40),
        ),
    ]
