# Generated by Django 4.2.7 on 2024-01-10 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0018_delete_userfacturacion'),
        ('users', '0005_pasajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='puesto',
            field=models.OneToOneField(default=200, on_delete=django.db.models.deletion.DO_NOTHING, to='lib.puestos'),
        ),
    ]
