# Generated by Django 4.2.7 on 2024-01-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_pasajero_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfacturacion',
            name='situacionFiscal',
            field=models.CharField(choices=[('Persona Natural', 'Persona Natural'), ('Persona Juridica', 'Persona Juridica')], max_length=40),
        ),
        migrations.AlterField(
            model_name='userfacturacion',
            name='tipoDeDocumento',
            field=models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('Pasaporte', 'Pasaporte')], max_length=40),
        ),
    ]
