# Generated by Django 4.2.7 on 2024-09-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userfacturacion_situacionfiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Ingresa el apellido'),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='ciudadDeResidencia',
            field=models.CharField(max_length=40, verbose_name='Ingresa la ciudad'),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Ingresa el nombre'),
        ),
    ]
